title: Martin Swinkels
author:
  name: Martin Swinkels
  email: #martin.swinkels+blog@msc365@@eu
  address: Lagos, Algarve Portugal
description: > # this means to ignore newlines until "show_excerpts:"
  Connecting the dots on Azure, Power Platform, and Azure DevOps.

url: https://msc365.eu/

name: Martin Swinkels
subtitle: Technical specialist on Azure, Power Platform, and Azure DevOps.
logo: https://msc365.eu/assets/img/msc365-cloud-256.png

show_excerpts: true # set to false to hide excerpts on the homepage
show_drafts: false

paginate: 10
paginate_path: "/:num/"

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: auto
  # generate social links in footer
  social_links:
    # - { platform: devto,          user_url: "https://dev.to/jekyll" }
    # - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
    # - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
    # - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
    - { platform: github,         user_url: "https://github.com/mccmswinkels" }
    # - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
    # - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
    # - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/mccmswinkels" }
    # - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
    # - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
    # - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
    # - { platform: telegram,       user_url: "https://t.me/jekyll" }
    - { platform: twitter,        user_url: "https://twitter.com/mccmswinkels" }
    # - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- categories/portfolio.md
- policy.md
- about.md

# Build settings
theme: minima

disqus:
  shortname: msc365-blog

google_analytics: G-V8HPDSD10T

plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-paginateS
